#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias vi=vim
alias please='sudo $(fc -ln -1)'

### BEGIN keychain ###
if which keychain >& /dev/null; then
    keychain --agents ssh id_rsa id_ed25519
    source $HOME/.keychain/$(hostname)-sh
fi
### END keychain ###

export PATH=$HOME/bin:$PATH
export PATH=$HOME/go/bin:$PATH

if which kubectl >& /dev/null; then
    source <(kubectl completion zsh)
fi

if [ -f $HOME/.ghcup/env ]; then
    source $HOME/.ghcup/env
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/hoa.nguyen.thai/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/hoa.nguyen.thai/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/hoa.nguyen.thai/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/hoa.nguyen.thai/google-cloud-sdk/completion.zsh.inc'; fi
